### ISSUE TITLE
Maintenance plans

### ISSUE THREAD

**Issue by jaraco** [Lucretiel/autocommand#22]
After reading #20, I'm beginning to worry that this project is abandoned. I've used it across many projects and would like to continue to use it, but if the test suite is not passing on the latest released version, I have concerns that it may not be maintained.

I'd be willing to help out with maintenance. If you'd like a co-maintainer, please add me as as a committer to the repo and maintainer of the project in PyPI. If you'd like to hand off maintenance, I'll take that on as well - just transfer the github repo to jaraco and ownership of PyPI to me. If you have plans/vision for the project that you'd like me to honor, let me know.

Thanks for this project and any aid you may be able to provide.

**Comment by mtelka** [comment]
@Lucretiel: +1 for adding @jaraco as a co-maintainer or fully transferring the project to him.  Thanks.

**Comment by Lucretiel** [comment]
Hey there! No, it's not abandoned, I just haven't had time or energy to work on it in a while. I'm not willing to transfer ownership right now but I'm happy to review and merge pull requests; the major piece of maintenance work I know is needed is to move away from `asyncio.async`, since that was added as a keyword.

**Comment by mtelka** [comment]
As pointed out in #20, the problem with `asyncio.async` seems to be already fixed via 031c9750c74e3313b954b09e3027aaa6595649bb.  The only thing needed to solve that definitely is just new `autocommand` release.

**Comment by Lucretiel** [comment]
Published 2.2.2, which should resolve this. Let me know if there are additional issues.
