### ISSUE TITLE
Badge for travis

### ISSUE THREAD

**Issue by jaraco** [Lucretiel/autocommand#24]
I see this project uses Travis CI, but I don't see any link to the runs, I tried guessing what the URL would be, but I haven't used Travis CI in so long that I don't remember what the syntax is to locate a project in Travis CI. It would be nice if the readme provided a link.

**Comment by Lucretiel** [comment]
Good catch; I moved away from travis CI ages ago when they went to their commercialized form. Added a github CI in https://github.com/Lucretiel/autocommand/pull/26 and added a badge tracking it. Thanks for the report!
